# Generated by Django 3.2.6 on 2021-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(default='00'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='item_img/default.png', upload_to='item_img'),
        ),
    ]
